### ISSUE TITLE
Broken sources link in readme.adoc

### ISSUE THREAD

**Issue by AmishNick** [bitcoin-dev-philosophy/btcphilosophy#41]
The link to external resources in the Readme document doesn't work. Currently it links to:

 https://github.com/bitcoin-dev-philosophy/btcphilosophy/blob/master/sources/sources.html

It should link to:

https://github.com/bitcoin-dev-philosophy/btcphilosophy/blob/master/sources/sources.adoc

**Comment by adamjonas** [comment]
Quite difficult to do as discussed on #42
