### ISSUE TITLE
[1.16.23] Alternatives to Decentralization Banner

### ISSUE THREAD

**Issue by jarolrod** [bitcoin-dev-philosophy/btcphilosophy#53]
These are some alternatives to the decentralized banner unedited and raw. If you guys like any of these more than the current one, I can submit a PR; otherwise if none are appealing, feel free to close.

## A. 
![grid_0-9](https://user-images.githubusercontent.com/23396902/212632267-48dda87d-bd3d-41d2-a6fc-79683f8ba32e.png)

## B.
![grid_0-12](https://user-images.githubusercontent.com/23396902/212632358-53bf4ad6-3950-4da7-9968-1824419977f0.png)

## C.
![grid_0-11](https://user-images.githubusercontent.com/23396902/212632394-3685f75e-7dce-489b-a555-9e0c586f8d47.png)

## D. 
![grid_0-13](https://user-images.githubusercontent.com/23396902/212632482-15562cdd-302e-4371-b472-ee994611c4fc.png)

## E.
![grid_0-8](https://user-images.githubusercontent.com/23396902/212632563-a0f37a96-e48a-49cb-b33d-852cab15df71.png)

## F.
![grid_0-10](https://user-images.githubusercontent.com/23396902/212632622-1420250a-73a6-4f80-b226-e81371cd8f5f.png)

## G.
![grid_0-6](https://user-images.githubusercontent.com/23396902/212632756-f114f76c-32e3-4585-900d-06aad7ea574d.png)

## H.

![grid_0-5](https://user-images.githubusercontent.com/23396902/212632816-5734ffd8-8e68-4941-8875-1b5c9c0cfc82.png)

## I.

![grid_0-7](https://user-images.githubusercontent.com/23396902/212632970-bb620c09-88a0-4af6-a488-cb35ed1a5626.png)

**Comment by kallerosenbaum** [comment]
I like 'I' best because it's not so homogeneous. I think it gives a good mental model of the Bitcoin landscape.

**Comment by MartaTurchetta** [comment]
I agree with @kallerosenbaum : images like the current one and the alternative I give a good visual representation of decentralization, as opposed to some of the other images where it is not as clear that all the machines are interconnected.
I also feel that alternatives B and D are able to convey the idea of how a decentralized system functions. From an aesthetic point of view though, I is probably the nicest. Opinions?

**Comment by kallerosenbaum** [comment]
Since we merged #61, I'll close this issue.
