### ISSUE TITLE
[1.16.23] Alternatives to Adversarial Thinking Banner

### ISSUE THREAD

**Issue by jarolrod** [bitcoin-dev-philosophy/btcphilosophy#55]
These are some alternatives to the adversarial section banner unedited and raw. If you guys like any of these more than the current one, I can submit a PR; otherwise if none are appealing, feel free to close.

Some of these are from previous section alternative image sets as they also apply to this section.

## A.

![grid_0-14](https://user-images.githubusercontent.com/23396902/212636322-4b5af9c5-efff-4066-9cc5-8705881fc635.png)

## B.

![grid_0-15](https://user-images.githubusercontent.com/23396902/212636405-5cea9081-60e1-4fb8-9fd4-6461db4066ae.png)

## C.
![grid_0-18](https://user-images.githubusercontent.com/23396902/212636465-3a6506d8-843e-4502-8a45-4f93288c1512.png)

## D.
![grid_0-16](https://user-images.githubusercontent.com/23396902/212636572-6ad2cecf-0989-4bd3-a8ca-ae9e2241432b.png)

## E.

![grid_0-25](https://user-images.githubusercontent.com/23396902/212637241-308c5d25-52af-4354-a734-bdc0a6c8d866.png)

## F.
![grid_0-26](https://user-images.githubusercontent.com/23396902/212637278-96ef6adc-7c21-413d-a6b8-44a715df1f27.png)

## G (This is pretty funny).

![grid_0-27](https://user-images.githubusercontent.com/23396902/212637376-add2d3bc-d7e5-49dd-9853-eb88446019d1.png)

**Comment by linnearosenbaum** [comment]
Hi! I really like these banner, great work! Especially the more abstract ones. Some comments:

1. I agree that Adversarial thinking G is funny. And better than the merged one.
2. I like the idea with bedroom in Privacy Banner options. Especially D
3. The opensource and upgrading banners on master branch feels (for me) excluding and old-fashioned with only middle aged/young men depicted.

Again, nice work :)

**Comment by jarolrod** [comment]
@linnearosenbaum thanks for the feedback! Working to open the PR's for the Adversarial Thinking and Privacy sections

On The open source and upgrading sections, I don't have fine grained control of all the parameters of the people that midjourney will draw, but I can attempt address that through some reimagining of the images

**Comment by linnearosenbaum** [comment]
I understand completely, again great work!

/Linnéa

**Comment by kallerosenbaum** [comment]
Since we merged #57, I'll close this issue.
