### ISSUE TITLE
[1.16.23] Alternatives to Trustlessness Banner

### ISSUE THREAD

**Issue by jarolrod** [bitcoin-dev-philosophy/btcphilosophy#56]
These are some alternatives to the Trustlessness banner unedited and raw. Bitcoin references can be photoshopped in. If you guys like any of these more than the current one, I can submit a PR; otherwise if none are appealing, feel free to close.

## A.
![grid_0-32](https://user-images.githubusercontent.com/23396902/212638776-3ac9ac01-05a8-4e9e-94f7-6961eecabbd7.png)

## B.
![DALL·E 2023-01-14 13 23 00 - continuation of the scene](https://user-images.githubusercontent.com/23396902/212639529-2952f3d9-2ecd-432e-bbe4-899e34b19968.png)

## C.
![grid_0-28](https://user-images.githubusercontent.com/23396902/212638873-5595a497-6933-48e0-9c7a-a72c2b67c1d4.png)

## D.
![grid_0-29](https://user-images.githubusercontent.com/23396902/212638937-d565a116-503b-480e-96a9-2b8fdcfa626d.png)

## E.

![grid_0-31](https://user-images.githubusercontent.com/23396902/212638987-ebbf82a5-18ca-4457-9607-7a8fdbae38a9.png)

## F.
![grid_0-30](https://user-images.githubusercontent.com/23396902/212639111-6ad364b1-f309-4a06-b948-2b7b0dc21999.png)

**Comment by kallerosenbaum** [comment]
F is very nice

**Comment by kallerosenbaum** [comment]
Closing this, since we wanted to keep the original image in the end, and closed PR #62.
