### ISSUE TITLE
Switch to technical xrefs for first few chapters

### ISSUE THREAD

**Issue by kallerosenbaum** [bitcoin-dev-philosophy/btcphilosophy#74]
See conversation here: https://github.com/bitcoin-dev-philosophy/btcphilosophy/pull/70#discussion_r1094980249

Switch to technical xrefs for chapters (if there are any to fix)
* Readme
* Decentralization
* Trustlessness
* Privacy

**Comment by kallerosenbaum** [comment]
Actually the xrefs should be verified across the full book. Just to make sure.

**Comment by kallerosenbaum** [comment]
In hindsight, this commit requires review. @MartaTurchetta could you check that I'm not messing stuff up here?

**Comment by kallerosenbaum** [comment]
Marta's thumbs up: https://github.com/bitcoin-dev-philosophy/btcphilosophy/pull/89#pullrequestreview-1379589528

**Comment by MartaTurchetta** [comment]
@kallerosenbaum I'm sorry but I lost track here. Do you want me to check all the xrefs in the book? I'm happy to do it but please help me out a little bit :)

1. Have you checked the first few chapters (up to "Privacy" if I'm not mistaking)?
2. Have you also checked the rest of them or do you want me to do it (as we agreed I would)?
3. Which is the exact form that the refs should have?

So sorry this piece of work slipped away, if you help me answer these 3 questions I'll check it out asap

**Comment by kallerosenbaum** [comment]
I think this is already done. This issue is closed and merged, as you've already given you thumbs up here: https://github.com/bitcoin-dev-philosophy/btcphilosophy/pull/89#pullrequestreview-1379589

So nothing more to do here.
